1.60b

diff --git a/afl-cmin b/afl-cmin
--- a/afl-cmin
+++ b/afl-cmin
@@ -142,7 +142,7 @@ echo "$PWD" | grep -qE '^(/var)?/tmp/'
 T5="$?"
 
 if [ "$T1" = "0" -o "$T2" = "0" -o "$T3" = "0" -o "$T4" = "0" -o "$T5" = "0" ]; then
-  echo "Error: do not use this script in /tmp or /var/tmp." 1>&2
+  echo "[-] Error: do not use this script in /tmp or /var/tmp." 1>&2
   exit 1
 fi
 
@@ -384,7 +384,7 @@ sort -k1,1 -s -u "$TRACE_DIR/.candidate_list" | \
   sed 's/^/BEST_FILE[/;s/ /]="/;s/$/"/' >"$TRACE_DIR/.candidate_script"
 
 if [ ! -s "$TRACE_DIR/.candidate_script" ]; then
-  echo "[-] ERROR: No traces obtained from test cases, check syntax!"
+  echo "[-] Error: no traces obtained from test cases, check syntax!"
   test "$AFL_KEEP_TRACES" = "" && rm -rf "$TRACE_DIR"
   exit 1
 fi
diff --git a/afl-plot b/afl-plot
--- a/afl-plot
+++ b/afl-plot
@@ -46,14 +46,14 @@ T2="$?"
 
 if [ "$T1" = "0" -o "$T2" = "0" ]; then
 
-  echo "Error: do not use shared /tmp or /var/tmp directories with this script." 1>&2
+  echo "[-] Error: this script shouldn't be used with shared /tmp directories." 1>&2
   exit 1
 
 fi
 
 if [ ! -f "$1/plot_data" ]; then
 
-  echo "[-] The input directory is not valid (missing 'plot_data')." 1>&2
+  echo "[-] Error: input directory is not valid (missing 'plot_data')." 1>&2
   exit 1
 
 fi
@@ -66,7 +66,7 @@ GNUPLOT=`which gnuplot 2>/dev/null`
 
 if [ "$GNUPLOT" = "" ]; then
 
-  echo "[-] Can't find 'gnuplot' in your \$PATH - do you have it installed?" 1>&2
+  echo "[-] Error: can't find 'gnuplot' in your \$PATH." 1>&2
   exit 1
 
 fi
@@ -75,7 +75,7 @@ mkdir "$2" 2>/dev/null
 
 if [ ! -d "$2" ]; then
 
-  echo "[-] Unable to create the output directory - pick another location." 1>&2
+  echo "[-] Error: unable to create the output directory - pick another location." 1>&2
   exit 1
 
 fi
@@ -134,7 +134,7 @@ _EOF_
 
 if [ ! -s "$2/exec_speed.png" ]; then
 
-  echo "[-] Oops, something went wrong! Perhaps you have an ancient or broken version of gnuplot?" 1>&2
+  echo "[-] Error: something went wrong! Perhaps you have an ancient version of gnuplot?" 1>&2
   exit 1
 
 fi
